Repository gardener/machine-controller-manager-provider-aws, pull requests merged in 2021-09, with the labels that each got.

#41 init upgrade prs
  .ci/component_descriptor
  .ci/pipeline_definitions
  .ci/set_dependency_version
  MCM_VERSION
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#44 Finalise upgrade prs
  .ci/pipeline_definitions
  .ci/set_dependency_version
Labels: needs/ok-to-test, needs/review, size/s

#46 go version for steps in pipeline upgraded
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#48 Updates test step of pipeline to use testmachinery base-step image
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
