Repository gardener/machine-controller-manager-provider-aws, pull requests merged in 2021-04, with the labels that each got.

#29 Add capacity reservation support
  kubernetes/machine-class.yaml
  pkg/aws/apis/aws_provider_spec.go
  pkg/aws/apis/validation/validation.go
  pkg/aws/core.go
  pkg/aws/core_test.go
Labels: reviewed/lgtm, size/s

#30 Added a provider check for the machine class in all the driver methods
  .gitignore
  kubernetes/machine-class.yaml
  pkg/aws/aws_suite_test.go
  pkg/aws/core.go
  pkg/aws/core_test.go
Labels: merge/squash, needs/ok-to-test, reviewed/lgtm, size/m

#32 introduced logic to set "Placement" field in machine using annotations
  .gitignore
  kubernetes/machine-deployment.yaml
  kubernetes/machine.yaml
  pkg/aws/aws_suite_test.go
  pkg/aws/core.go
  pkg/aws/core_test.go
  pkg/aws/util.go
  pkg/mockclient/mockclient.go
Labels: needs/second-opinion, size/l

#33 Fixes linting issues
  pkg/aws/apis/aws_provider_spec.go
  pkg/aws/apis/validation/validation.go
  pkg/aws/core.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
