Repository gardener/machine-controller-manager-provider-aws, pull requests merged in 2022-03, with the labels that each got.

#67 [rel-v0.9] Automated cherry pick of #65: Use proper version of klog
  go.mod
  go.sum
  pkg/aws/core.go
  pkg/aws/core_util.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: area/dev-productivity, area/ops-productivity, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#68 SrcDestCheck changes done after confirming consistency
  pkg/aws/core.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#74 Correction in auto-revendoring script
  .ci/set_dependency_version
Labels: needs/ok-to-test, needs/review, size/xs

#75 testing to see auto-vendor works
  MCM_VERSION
Labels: needs/ok-to-test, needs/review, size/xs
